"""empty message

Revision ID: 07da22a81395
Revises: 5343fea64cd0
Create Date: 2024-08-18 03:48:58.965021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07da22a81395'
down_revision = '5343fea64cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('current_class', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('admission_class', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('residence_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('current_school', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('nationality', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('alternative_number', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sibling', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sibling_num', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('parent_names', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('parent_', sa.BigInteger(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_students', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('parent_')
        batch_op.drop_column('parent_names')
        batch_op.drop_column('sibling_num')
        batch_op.drop_column('sibling')
        batch_op.drop_column('email')
        batch_op.drop_column('alternative_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('nationality')
        batch_op.drop_column('current_school')
        batch_op.drop_column('residence_name')
        batch_op.drop_column('admission_class')
        batch_op.drop_column('current_class')
        batch_op.drop_column('gender')
        batch_op.drop_column('dob')
        batch_op.drop_column('surname')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
