"""empty message

Revision ID: 59778d9f4828
Revises: 
Create Date: 2024-08-17 23:02:17.300464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59778d9f4828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_siblings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registered_students',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_teacher',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.BigInteger(), nullable=False),
    sa.Column('column_3', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('middle_name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('current_class', sa.Text(), nullable=False),
    sa.Column('admission_class', sa.Text(), nullable=False),
    sa.Column('residence_name', sa.Text(), nullable=False),
    sa.Column('current_school', sa.Text(), nullable=False),
    sa.Column('nationality', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('alternative_number', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('sibling', sa.Boolean(), nullable=False),
    sa.Column('sibling_num', sa.BigInteger(), nullable=False),
    sa.Column('parent_names', sa.Text(), nullable=False),
    sa.Column('parent_', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('registered_student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['registered_student_id'], ['registered_students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_student_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.BigInteger(), nullable=False),
    sa.Column('column_3', sa.BigInteger(), nullable=False),
    sa.Column('subject_teacher_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['subject_teacher_id'], ['subject_teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspended_students',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('class_', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('sus_no', sa.BigInteger(), nullable=False),
    sa.Column('registered_student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['registered_student_id'], ['registered_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['registered_students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('suspended_students')
    op.drop_table('subjects')
    op.drop_table('student_applications')
    op.drop_table('teachers')
    op.drop_table('subject_teacher')
    op.drop_table('registered_students')
    op.drop_table('applicant_siblings')
    # ### end Alembic commands ###
